name: build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2.0.1
        with:
          arguments: build

      - name: Upload to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: library-jvm/build/reports/kover/report.xml,library-multiplatform/build/reports/kover/report.xml

      - name: Upload to Codacy
        if: ${{ always() }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: library-jvm/build/reports/kover/report.xml,library-multiplatform/build/reports/kover/report.xml
